// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delivery.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, order_id, restaurant_id, customer_id, status, street, city, zip_code, courier_id, courier_name, created_at, updated_at FROM deliveries WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RestaurantID,
		&i.CustomerID,
		&i.Status,
		&i.Street,
		&i.City,
		&i.ZipCode,
		&i.CourierID,
		&i.CourierName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnpublishedOutboxMessages = `-- name: GetUnpublishedOutboxMessages :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, correlation_id, created_at, published_at FROM outbox_messages WHERE published_at IS NULL ORDER BY created_at ASC
`

func (q *Queries) GetUnpublishedOutboxMessages(ctx context.Context) ([]OutboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, getUnpublishedOutboxMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (
    id, aggregate_type, aggregate_id, event_type, payload, correlation_id
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertOutboxMessageParams struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
	)
	return err
}

const isMessageProcessed = `-- name: IsMessageProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_messages WHERE message_id = ?)
`

func (q *Queries) IsMessageProcessed(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMessageProcessed, messageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markMessageAsProcessed = `-- name: MarkMessageAsProcessed :exec
INSERT INTO processed_messages (message_id) VALUES (?)
`

func (q *Queries) MarkMessageAsProcessed(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, markMessageAsProcessed, messageID)
	return err
}

const markOutboxMessageAsPublished = `-- name: MarkOutboxMessageAsPublished :exec
UPDATE outbox_messages SET published_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkOutboxMessageAsPublished(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markOutboxMessageAsPublished, id)
	return err
}

const saveDelivery = `-- name: SaveDelivery :exec
INSERT INTO deliveries (
    id, order_id, restaurant_id, customer_id, status, street, city, zip_code, courier_id, courier_name
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY UPDATE
    status = VALUES(status),
    courier_id = VALUES(courier_id),
    courier_name = VALUES(courier_name),
    updated_at = CURRENT_TIMESTAMP
`

type SaveDeliveryParams struct {
	ID           string         `db:"id" json:"id"`
	OrderID      string         `db:"order_id" json:"order_id"`
	RestaurantID string         `db:"restaurant_id" json:"restaurant_id"`
	CustomerID   string         `db:"customer_id" json:"customer_id"`
	Status       string         `db:"status" json:"status"`
	Street       string         `db:"street" json:"street"`
	City         string         `db:"city" json:"city"`
	ZipCode      string         `db:"zip_code" json:"zip_code"`
	CourierID    sql.NullString `db:"courier_id" json:"courier_id"`
	CourierName  sql.NullString `db:"courier_name" json:"courier_name"`
}

func (q *Queries) SaveDelivery(ctx context.Context, arg SaveDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, saveDelivery,
		arg.ID,
		arg.OrderID,
		arg.RestaurantID,
		arg.CustomerID,
		arg.Status,
		arg.Street,
		arg.City,
		arg.ZipCode,
		arg.CourierID,
		arg.CourierName,
	)
	return err
}
