// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Delivery struct {
	ID           string         `db:"id" json:"id"`
	OrderID      string         `db:"order_id" json:"order_id"`
	RestaurantID string         `db:"restaurant_id" json:"restaurant_id"`
	CustomerID   string         `db:"customer_id" json:"customer_id"`
	Status       string         `db:"status" json:"status"`
	Street       string         `db:"street" json:"street"`
	City         string         `db:"city" json:"city"`
	ZipCode      string         `db:"zip_code" json:"zip_code"`
	CourierID    sql.NullString `db:"courier_id" json:"courier_id"`
	CourierName  sql.NullString `db:"courier_name" json:"courier_name"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}

type OutboxMessage struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	PublishedAt   sql.NullTime    `db:"published_at" json:"published_at"`
}

type ProcessedMessage struct {
	MessageID   string    `db:"message_id" json:"message_id"`
	ProcessedAt time.Time `db:"processed_at" json:"processed_at"`
}
