// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetDeliveryByID(ctx context.Context, id string) (Delivery, error)
	GetUnpublishedOutboxMessages(ctx context.Context) ([]OutboxMessage, error)
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	IsMessageProcessed(ctx context.Context, messageID string) (bool, error)
	MarkMessageAsProcessed(ctx context.Context, messageID string) error
	MarkOutboxMessageAsPublished(ctx context.Context, id string) error
	SaveDelivery(ctx context.Context, arg SaveDeliveryParams) error
}

var _ Querier = (*Queries)(nil)
