version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: food_project_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_project
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: food_project_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
