apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: food-ordering-ddd
build:
  local:
    push: false
  artifacts:
    - image: catalog-api
      context: .
      docker:
        dockerfile: catalog/Dockerfile
deploy:
  helm:
    releases:
      - name: catalog-release
        namespace: catalog
        chartPath: ./deploy/helm/ms-base
        valuesFiles:
          - ./catalog/values.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_catalog_api}}"
          image.tag: "{{.IMAGE_TAG_catalog_api}}"
