// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: ordering.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, customer_id, restaurant_id, status, total_amount, currency, delivery_address, correlation_id, version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID              string    `json:"id"`
	CustomerID      string    `json:"customer_id"`
	RestaurantID    string    `json:"restaurant_id"`
	Status          string    `json:"status"`
	TotalAmount     int64     `json:"total_amount"`
	Currency        string    `json:"currency"`
	DeliveryAddress string    `json:"delivery_address"`
	CorrelationID   string    `json:"correlation_id"`
	Version         int32     `json:"version"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.RestaurantID,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.DeliveryAddress,
		arg.CorrelationID,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (id, order_id, menu_item_id, name, quantity, unit_price, notes)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	ID         string         `json:"id"`
	OrderID    string         `json:"order_id"`
	MenuItemID string         `json:"menu_item_id"`
	Name       string         `json:"name"`
	Quantity   int32          `json:"quantity"`
	UnitPrice  int64          `json:"unit_price"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.MenuItemID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.Notes,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, restaurant_id, status, total_amount, currency, delivery_address, correlation_id, version, created_at, updated_at FROM orders WHERE id = ?
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RestaurantID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryAddress,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaState = `-- name: GetSagaState :one
SELECT order_id, current_step, status, data_json, updated_at FROM saga_state WHERE order_id = ?
`

func (q *Queries) GetSagaState(ctx context.Context, orderID string) (SagaState, error) {
	row := q.db.QueryRowContext(ctx, getSagaState, orderID)
	var i SagaState
	err := row.Scan(
		&i.OrderID,
		&i.CurrentStep,
		&i.Status,
		&i.DataJson,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, menu_item_id, name, quantity, unit_price, notes FROM order_items WHERE order_id = ?
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, customer_id, restaurant_id, status, total_amount, currency, delivery_address, correlation_id, version, created_at, updated_at FROM orders WHERE customer_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RestaurantID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.DeliveryAddress,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOutboxMessage = `-- name: SaveOutboxMessage :exec
INSERT INTO outbox_messages (id, aggregate_type, aggregate_id, event_type, payload, correlation_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type SaveOutboxMessageParams struct {
	ID            string          `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	CorrelationID string          `json:"correlation_id"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) SaveOutboxMessage(ctx context.Context, arg SaveOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, saveOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
		arg.CreatedAt,
	)
	return err
}

const saveSagaState = `-- name: SaveSagaState :exec
INSERT INTO saga_state (order_id, current_step, status, data_json, updated_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE 
    current_step = VALUES(current_step),
    status = VALUES(status),
    data_json = VALUES(data_json),
    updated_at = VALUES(updated_at)
`

type SaveSagaStateParams struct {
	OrderID     string          `json:"order_id"`
	CurrentStep string          `json:"current_step"`
	Status      string          `json:"status"`
	DataJson    json.RawMessage `json:"data_json"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) SaveSagaState(ctx context.Context, arg SaveSagaStateParams) error {
	_, err := q.db.ExecContext(ctx, saveSagaState,
		arg.OrderID,
		arg.CurrentStep,
		arg.Status,
		arg.DataJson,
		arg.UpdatedAt,
	)
	return err
}

const updateOrderWithVersion = `-- name: UpdateOrderWithVersion :exec
UPDATE orders 
SET status = ?, version = version + 1, updated_at = ?
WHERE id = ? AND version = ?
`

type UpdateOrderWithVersionParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	Version   int32     `json:"version"`
}

func (q *Queries) UpdateOrderWithVersion(ctx context.Context, arg UpdateOrderWithVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderWithVersion,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	return err
}
