// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	GetOrder(ctx context.Context, id string) (Order, error)
	GetSagaState(ctx context.Context, orderID string) (SagaState, error)
	ListOrderItems(ctx context.Context, orderID string) ([]OrderItem, error)
	ListOrdersByCustomer(ctx context.Context, customerID string) ([]Order, error)
	SaveOutboxMessage(ctx context.Context, arg SaveOutboxMessageParams) error
	SaveSagaState(ctx context.Context, arg SaveSagaStateParams) error
	UpdateOrderWithVersion(ctx context.Context, arg UpdateOrderWithVersionParams) error
}

var _ Querier = (*Queries)(nil)
