apiVersion: v1
kind: Namespace
metadata:
  name: shared-infra
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
  labels:
    istio.io/dataplane-mode: ambient
