apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: shared-infra
data:
  rabbitmq.conf: |
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "users": [
        {"name": "admin", "password": "admin", "tags": "administrator"},
        {"name": "catalog", "password": "catalog", "tags": "management"}
      ],
      "vhosts": [
        {"name": "/"}
      ],
      "permissions": [
        {"user": "admin", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"},
        {"user": "catalog", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"}
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: shared-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
      - name: rabbitmq-config-vol
        configMap:
          name: rabbitmq-config
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13-management
        volumeMounts:
        - name: rabbitmq-config-vol
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-config-vol
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: shared-infra
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
