apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db
  namespace: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:latest
        env:
        - name: MYSQL_DATABASE
          value: "catalog-db"
        - name: MYSQL_ROOT_PASSWORD
          value: "mysqlroot"
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: catalog
spec:
  selector:
    app: catalog-db
  ports:
  - port: 3306
    targetPort: 3306
