{{- if .Values.istio.gateway.create -}}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name | default (printf "%s-gateway" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{- range .Values.istio.gateway.hosts }}
      - {{ . | quote }}
      {{- end }}
{{- end }}
