// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: catalog_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRestaurantAndItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemsId       []string               `protobuf:"bytes,2,rep,name=items_id,json=itemsId,proto3" json:"items_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRestaurantAndItemsRequest) Reset() {
	*x = ValidateRestaurantAndItemsRequest{}
	mi := &file_catalog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRestaurantAndItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRestaurantAndItemsRequest) ProtoMessage() {}

func (x *ValidateRestaurantAndItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRestaurantAndItemsRequest.ProtoReflect.Descriptor instead.
func (*ValidateRestaurantAndItemsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRestaurantAndItemsRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *ValidateRestaurantAndItemsRequest) GetItemsId() []string {
	if x != nil {
		return x.ItemsId
	}
	return nil
}

type ValidateRestaurantAndItemsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Valid            bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Items            []*ItemSnapshot        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ValidationErrors []string               `protobuf:"bytes,3,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateRestaurantAndItemsResponse) Reset() {
	*x = ValidateRestaurantAndItemsResponse{}
	mi := &file_catalog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRestaurantAndItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRestaurantAndItemsResponse) ProtoMessage() {}

func (x *ValidateRestaurantAndItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRestaurantAndItemsResponse.ProtoReflect.Descriptor instead.
func (*ValidateRestaurantAndItemsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRestaurantAndItemsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateRestaurantAndItemsResponse) GetItems() []*ItemSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ValidateRestaurantAndItemsResponse) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

type ItemSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSnapshot) Reset() {
	*x = ItemSnapshot{}
	mi := &file_catalog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSnapshot) ProtoMessage() {}

func (x *ItemSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSnapshot.ProtoReflect.Descriptor instead.
func (*ItemSnapshot) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{2}
}

func (x *ItemSnapshot) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemSnapshot) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

var File_catalog_service_proto protoreflect.FileDescriptor

const file_catalog_service_proto_rawDesc = "" +
	"\n" +
	"\x15catalog_service.proto\x12\acatalog\"c\n" +
	"!ValidateRestaurantAndItemsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x19\n" +
	"\bitems_id\x18\x02 \x03(\tR\aitemsId\"\x94\x01\n" +
	"\"ValidateRestaurantAndItemsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.catalog.ItemSnapshotR\x05items\x12+\n" +
	"\x11validation_errors\x18\x03 \x03(\tR\x10validationErrors\"\\\n" +
	"\fItemSnapshot\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents2\x87\x01\n" +
	"\x0eCatalogService\x12u\n" +
	"\x1aValidateRestaurantAndItems\x12*.catalog.ValidateRestaurantAndItemsRequest\x1a+.catalog.ValidateRestaurantAndItemsResponseBIZGgithub.com/vterry/food-ordering/catalog/internal/adapters/input/grpc/pbb\x06proto3"

var (
	file_catalog_service_proto_rawDescOnce sync.Once
	file_catalog_service_proto_rawDescData []byte
)

func file_catalog_service_proto_rawDescGZIP() []byte {
	file_catalog_service_proto_rawDescOnce.Do(func() {
		file_catalog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_service_proto_rawDesc), len(file_catalog_service_proto_rawDesc)))
	})
	return file_catalog_service_proto_rawDescData
}

var file_catalog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_service_proto_goTypes = []any{
	(*ValidateRestaurantAndItemsRequest)(nil),  // 0: catalog.ValidateRestaurantAndItemsRequest
	(*ValidateRestaurantAndItemsResponse)(nil), // 1: catalog.ValidateRestaurantAndItemsResponse
	(*ItemSnapshot)(nil),                       // 2: catalog.ItemSnapshot
}
var file_catalog_service_proto_depIdxs = []int32{
	2, // 0: catalog.ValidateRestaurantAndItemsResponse.items:type_name -> catalog.ItemSnapshot
	0, // 1: catalog.CatalogService.ValidateRestaurantAndItems:input_type -> catalog.ValidateRestaurantAndItemsRequest
	1, // 2: catalog.CatalogService.ValidateRestaurantAndItems:output_type -> catalog.ValidateRestaurantAndItemsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_service_proto_init() }
func file_catalog_service_proto_init() {
	if File_catalog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_service_proto_rawDesc), len(file_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_service_proto_goTypes,
		DependencyIndexes: file_catalog_service_proto_depIdxs,
		MessageInfos:      file_catalog_service_proto_msgTypes,
	}.Build()
	File_catalog_service_proto = out.File
	file_catalog_service_proto_goTypes = nil
	file_catalog_service_proto_depIdxs = nil
}
