replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

istio:
  gateway:
    create: true
    name: "food-ddd-gateway"
    hosts:
      - "*"
  virtualService:
    create: true
    prefix: "/"

auth:
  enabled: false
  jwt:
    issuer: ""
    jwksUri: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
