image:
  repository: catalog-api
  tag: latest # Substituído pelo Skaffold

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  HTTP_PORT: ":8080"
  GRPC_PORT: ":9090"
  DB_HOST: "catalog-db.catalog.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASS: "mysqlroot"
  DB_NAME: "catalog-db"
  RABBIT_HOST: "rabbitmq.shared-infra.svc.cluster.local"
  RABBIT_PORT: "5672"
  RABBIT_USER: "catalog"
  RABBIT_PASS: "catalog"

auth:
  enabled: true
  jwt:
    issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.29/security/tools/jwt/samples/jwks.json"

istio:
  gateway:
    create: true
    hosts:
      - "*"
  virtualService:
    create: true
    prefix: "/"
