// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: restaurant/api/proto/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_api_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *GetMenuItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type MenuItemResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId   string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	RestaurantName string                 `protobuf:"bytes,3,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price          float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Currency       string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Available      bool                   `protobuf:"varint,8,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MenuItemResponse) Reset() {
	*x = MenuItemResponse{}
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemResponse) ProtoMessage() {}

func (x *MenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemResponse.ProtoReflect.Descriptor instead.
func (*MenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_api_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItemResponse) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *MenuItemResponse) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *MenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItemResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MenuItemResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuItemsRequest) Reset() {
	*x = ListMenuItemsRequest{}
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuItemsRequest) ProtoMessage() {}

func (x *ListMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*ListMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_api_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListMenuItemsRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type ListMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItemResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuItemsResponse) Reset() {
	*x = ListMenuItemsResponse{}
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuItemsResponse) ProtoMessage() {}

func (x *ListMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_api_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*ListMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_api_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListMenuItemsResponse) GetItems() []*MenuItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_restaurant_api_proto_catalog_proto protoreflect.FileDescriptor

const file_restaurant_api_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\"restaurant/api/proto/catalog.proto\x12\n" +
	"restaurant\"R\n" +
	"\x12GetMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"\xf6\x01\n" +
	"\x10MenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12'\n" +
	"\x0frestaurant_name\x18\x03 \x01(\tR\x0erestaurantName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1c\n" +
	"\tavailable\x18\b \x01(\bR\tavailable\";\n" +
	"\x14ListMenuItemsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"K\n" +
	"\x15ListMenuItemsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.restaurant.MenuItemResponseR\x05items2\xb7\x01\n" +
	"\x0eCatalogService\x12M\n" +
	"\vGetMenuItem\x12\x1e.restaurant.GetMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\"\x00\x12V\n" +
	"\rListMenuItems\x12 .restaurant.ListMenuItemsRequest\x1a!.restaurant.ListMenuItemsResponse\"\x00B5Z3github.com/vterry/food-project/restaurant/api/protob\x06proto3"

var (
	file_restaurant_api_proto_catalog_proto_rawDescOnce sync.Once
	file_restaurant_api_proto_catalog_proto_rawDescData []byte
)

func file_restaurant_api_proto_catalog_proto_rawDescGZIP() []byte {
	file_restaurant_api_proto_catalog_proto_rawDescOnce.Do(func() {
		file_restaurant_api_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_api_proto_catalog_proto_rawDesc), len(file_restaurant_api_proto_catalog_proto_rawDesc)))
	})
	return file_restaurant_api_proto_catalog_proto_rawDescData
}

var file_restaurant_api_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_restaurant_api_proto_catalog_proto_goTypes = []any{
	(*GetMenuItemRequest)(nil),    // 0: restaurant.GetMenuItemRequest
	(*MenuItemResponse)(nil),      // 1: restaurant.MenuItemResponse
	(*ListMenuItemsRequest)(nil),  // 2: restaurant.ListMenuItemsRequest
	(*ListMenuItemsResponse)(nil), // 3: restaurant.ListMenuItemsResponse
}
var file_restaurant_api_proto_catalog_proto_depIdxs = []int32{
	1, // 0: restaurant.ListMenuItemsResponse.items:type_name -> restaurant.MenuItemResponse
	0, // 1: restaurant.CatalogService.GetMenuItem:input_type -> restaurant.GetMenuItemRequest
	2, // 2: restaurant.CatalogService.ListMenuItems:input_type -> restaurant.ListMenuItemsRequest
	1, // 3: restaurant.CatalogService.GetMenuItem:output_type -> restaurant.MenuItemResponse
	3, // 4: restaurant.CatalogService.ListMenuItems:output_type -> restaurant.ListMenuItemsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_restaurant_api_proto_catalog_proto_init() }
func file_restaurant_api_proto_catalog_proto_init() {
	if File_restaurant_api_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_api_proto_catalog_proto_rawDesc), len(file_restaurant_api_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_api_proto_catalog_proto_goTypes,
		DependencyIndexes: file_restaurant_api_proto_catalog_proto_depIdxs,
		MessageInfos:      file_restaurant_api_proto_catalog_proto_msgTypes,
	}.Build()
	File_restaurant_api_proto_catalog_proto = out.File
	file_restaurant_api_proto_catalog_proto_goTypes = nil
	file_restaurant_api_proto_catalog_proto_depIdxs = nil
}
