// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: menu.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearMenuItems = `-- name: ClearMenuItems :exec
DELETE FROM menu_items WHERE menu_id = ?
`

func (q *Queries) ClearMenuItems(ctx context.Context, menuID string) error {
	_, err := q.db.ExecContext(ctx, clearMenuItems, menuID)
	return err
}

const getActiveMenuByRestaurantID = `-- name: GetActiveMenuByRestaurantID :one
SELECT id, restaurant_id, name, is_active, created_at, updated_at FROM menus WHERE restaurant_id = ? AND is_active = TRUE
`

func (q *Queries) GetActiveMenuByRestaurantID(ctx context.Context, restaurantID string) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getActiveMenuByRestaurantID, restaurantID)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuByID = `-- name: GetMenuByID :one
SELECT id, restaurant_id, name, is_active, created_at, updated_at FROM menus WHERE id = ?
`

func (q *Queries) GetMenuByID(ctx context.Context, id string) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenuByID, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMenu = `-- name: InsertMenu :exec
INSERT INTO menus (id, restaurant_id, name, is_active)
VALUES (?, ?, ?, ?)
`

type InsertMenuParams struct {
	ID           string       `db:"id" json:"id"`
	RestaurantID string       `db:"restaurant_id" json:"restaurant_id"`
	Name         string       `db:"name" json:"name"`
	IsActive     sql.NullBool `db:"is_active" json:"is_active"`
}

func (q *Queries) InsertMenu(ctx context.Context, arg InsertMenuParams) error {
	_, err := q.db.ExecContext(ctx, insertMenu,
		arg.ID,
		arg.RestaurantID,
		arg.Name,
		arg.IsActive,
	)
	return err
}

const insertMenuItem = `-- name: InsertMenuItem :exec
INSERT INTO menu_items (id, menu_id, name, description, price_amount, price_currency, category, is_available)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMenuItemParams struct {
	ID            string         `db:"id" json:"id"`
	MenuID        string         `db:"menu_id" json:"menu_id"`
	Name          string         `db:"name" json:"name"`
	Description   sql.NullString `db:"description" json:"description"`
	PriceAmount   float64        `db:"price_amount" json:"price_amount"`
	PriceCurrency string         `db:"price_currency" json:"price_currency"`
	Category      string         `db:"category" json:"category"`
	IsAvailable   sql.NullBool   `db:"is_available" json:"is_available"`
}

func (q *Queries) InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) error {
	_, err := q.db.ExecContext(ctx, insertMenuItem,
		arg.ID,
		arg.MenuID,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Category,
		arg.IsAvailable,
	)
	return err
}

const listMenuItemsByMenuID = `-- name: ListMenuItemsByMenuID :many
SELECT id, menu_id, name, description, price_amount, price_currency, category, is_available, created_at, updated_at FROM menu_items WHERE menu_id = ?
`

func (q *Queries) ListMenuItemsByMenuID(ctx context.Context, menuID string) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItemsByMenuID, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.Description,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Category,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :exec
UPDATE menus SET name = ?, is_active = ?
WHERE id = ?
`

type UpdateMenuParams struct {
	Name     string       `db:"name" json:"name"`
	IsActive sql.NullBool `db:"is_active" json:"is_active"`
	ID       string       `db:"id" json:"id"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) error {
	_, err := q.db.ExecContext(ctx, updateMenu, arg.Name, arg.IsActive, arg.ID)
	return err
}

const updateMenuItem = `-- name: UpdateMenuItem :exec
UPDATE menu_items SET name = ?, description = ?, price_amount = ?, price_currency = ?, category = ?, is_available = ?
WHERE id = ?
`

type UpdateMenuItemParams struct {
	Name          string         `db:"name" json:"name"`
	Description   sql.NullString `db:"description" json:"description"`
	PriceAmount   float64        `db:"price_amount" json:"price_amount"`
	PriceCurrency string         `db:"price_currency" json:"price_currency"`
	Category      string         `db:"category" json:"category"`
	IsAvailable   sql.NullBool   `db:"is_available" json:"is_available"`
	ID            string         `db:"id" json:"id"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) error {
	_, err := q.db.ExecContext(ctx, updateMenuItem,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Category,
		arg.IsAvailable,
		arg.ID,
	)
	return err
}
