// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: outbox.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (id, aggregate_type, aggregate_id, event_type, payload, correlation_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOutboxMessageParams struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
	)
	return err
}
