// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	ClearMenuItems(ctx context.Context, menuID string) error
	GetActiveMenuByRestaurantID(ctx context.Context, restaurantID string) (Menu, error)
	GetMenuByID(ctx context.Context, id string) (Menu, error)
	GetRestaurantByID(ctx context.Context, id string) (Restaurant, error)
	GetTicketByID(ctx context.Context, id string) (Ticket, error)
	InsertMenu(ctx context.Context, arg InsertMenuParams) error
	InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) error
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	InsertRestaurant(ctx context.Context, arg InsertRestaurantParams) error
	InsertTicket(ctx context.Context, arg InsertTicketParams) error
	InsertTicketItem(ctx context.Context, arg InsertTicketItemParams) error
	ListMenuItemsByMenuID(ctx context.Context, menuID string) ([]MenuItem, error)
	ListTicketItemsByTicketID(ctx context.Context, ticketID string) ([]TicketItem, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) error
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error
}

var _ Querier = (*Queries)(nil)
