// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: restaurant.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, name, street, city, zip_code, operating_hours, created_at, updated_at FROM restaurants WHERE id = ?
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id string) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.ZipCode,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRestaurant = `-- name: InsertRestaurant :exec
INSERT INTO restaurants (id, name, street, city, zip_code, operating_hours)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRestaurantParams struct {
	ID             string          `db:"id" json:"id"`
	Name           string          `db:"name" json:"name"`
	Street         string          `db:"street" json:"street"`
	City           string          `db:"city" json:"city"`
	ZipCode        string          `db:"zip_code" json:"zip_code"`
	OperatingHours json.RawMessage `db:"operating_hours" json:"operating_hours"`
}

func (q *Queries) InsertRestaurant(ctx context.Context, arg InsertRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, insertRestaurant,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.ZipCode,
		arg.OperatingHours,
	)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
UPDATE restaurants SET name = ?, street = ?, city = ?, zip_code = ?, operating_hours = ?
WHERE id = ?
`

type UpdateRestaurantParams struct {
	Name           string          `db:"name" json:"name"`
	Street         string          `db:"street" json:"street"`
	City           string          `db:"city" json:"city"`
	ZipCode        string          `db:"zip_code" json:"zip_code"`
	OperatingHours json.RawMessage `db:"operating_hours" json:"operating_hours"`
	ID             string          `db:"id" json:"id"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, updateRestaurant,
		arg.Name,
		arg.Street,
		arg.City,
		arg.ZipCode,
		arg.OperatingHours,
		arg.ID,
	)
	return err
}
