// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: ticket.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, order_id, restaurant_id, status, reject_reason, created_at, updated_at FROM tickets WHERE id = ?
`

func (q *Queries) GetTicketByID(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RestaurantID,
		&i.Status,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :exec
INSERT INTO tickets (id, order_id, restaurant_id, status, reject_reason)
VALUES (?, ?, ?, ?, ?)
`

type InsertTicketParams struct {
	ID           string         `db:"id" json:"id"`
	OrderID      string         `db:"order_id" json:"order_id"`
	RestaurantID string         `db:"restaurant_id" json:"restaurant_id"`
	Status       string         `db:"status" json:"status"`
	RejectReason sql.NullString `db:"reject_reason" json:"reject_reason"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) error {
	_, err := q.db.ExecContext(ctx, insertTicket,
		arg.ID,
		arg.OrderID,
		arg.RestaurantID,
		arg.Status,
		arg.RejectReason,
	)
	return err
}

const insertTicketItem = `-- name: InsertTicketItem :exec
INSERT INTO ticket_items (ticket_id, product_id, name, quantity)
VALUES (?, ?, ?, ?)
`

type InsertTicketItemParams struct {
	TicketID  string `db:"ticket_id" json:"ticket_id"`
	ProductID string `db:"product_id" json:"product_id"`
	Name      string `db:"name" json:"name"`
	Quantity  int32  `db:"quantity" json:"quantity"`
}

func (q *Queries) InsertTicketItem(ctx context.Context, arg InsertTicketItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketItem,
		arg.TicketID,
		arg.ProductID,
		arg.Name,
		arg.Quantity,
	)
	return err
}

const listTicketItemsByTicketID = `-- name: ListTicketItemsByTicketID :many
SELECT id, ticket_id, product_id, name, quantity FROM ticket_items WHERE ticket_id = ?
`

func (q *Queries) ListTicketItemsByTicketID(ctx context.Context, ticketID string) ([]TicketItem, error) {
	rows, err := q.db.QueryContext(ctx, listTicketItemsByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketItem
	for rows.Next() {
		var i TicketItem
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ProductID,
			&i.Name,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets SET status = ?, reject_reason = ? WHERE id = ?
`

type UpdateTicketStatusParams struct {
	Status       string         `db:"status" json:"status"`
	RejectReason sql.NullString `db:"reject_reason" json:"reject_reason"`
	ID           string         `db:"id" json:"id"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.RejectReason, arg.ID)
	return err
}
