// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: cart.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE customer_id = ?
`

func (q *Queries) DeleteCart(ctx context.Context, customerID string) error {
	_, err := q.db.ExecContext(ctx, deleteCart, customerID)
	return err
}

const deleteCartItems = `-- name: DeleteCartItems :exec
DELETE FROM cart_items WHERE customer_id = ?
`

func (q *Queries) DeleteCartItems(ctx context.Context, customerID string) error {
	_, err := q.db.ExecContext(ctx, deleteCartItems, customerID)
	return err
}

const getCartByCustomerID = `-- name: GetCartByCustomerID :one
SELECT customer_id, restaurant_id, updated_at
FROM carts
WHERE customer_id = ?
`

func (q *Queries) GetCartByCustomerID(ctx context.Context, customerID string) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByCustomerID, customerID)
	var i Cart
	err := row.Scan(&i.CustomerID, &i.RestaurantID, &i.UpdatedAt)
	return i, err
}

const insertCart = `-- name: InsertCart :exec
INSERT INTO carts (customer_id, restaurant_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE restaurant_id = VALUES(restaurant_id)
`

type InsertCartParams struct {
	CustomerID   string         `db:"customer_id" json:"customer_id"`
	RestaurantID sql.NullString `db:"restaurant_id" json:"restaurant_id"`
}

func (q *Queries) InsertCart(ctx context.Context, arg InsertCartParams) error {
	_, err := q.db.ExecContext(ctx, insertCart, arg.CustomerID, arg.RestaurantID)
	return err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (customer_id, product_id, name, price_amount, price_currency, quantity, observation)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertCartItemParams struct {
	CustomerID    string         `db:"customer_id" json:"customer_id"`
	ProductID     string         `db:"product_id" json:"product_id"`
	Name          string         `db:"name" json:"name"`
	PriceAmount   float64        `db:"price_amount" json:"price_amount"`
	PriceCurrency string         `db:"price_currency" json:"price_currency"`
	Quantity      int32          `db:"quantity" json:"quantity"`
	Observation   sql.NullString `db:"observation" json:"observation"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem,
		arg.CustomerID,
		arg.ProductID,
		arg.Name,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Quantity,
		arg.Observation,
	)
	return err
}

const listCartItemsByCustomerID = `-- name: ListCartItemsByCustomerID :many
SELECT id, customer_id, product_id, name, price_amount, price_currency, quantity, observation
FROM cart_items
WHERE customer_id = ?
`

func (q *Queries) ListCartItemsByCustomerID(ctx context.Context, customerID string) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProductID,
			&i.Name,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Quantity,
			&i.Observation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
