// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: customer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearAddresses = `-- name: ClearAddresses :exec
DELETE FROM addresses WHERE customer_id = ?
`

func (q *Queries) ClearAddresses(ctx context.Context, customerID string) error {
	_, err := q.db.ExecContext(ctx, clearAddresses, customerID)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, name, email, phone, created_at, updated_at
FROM customers
WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, email, phone, created_at, updated_at
FROM customers
WHERE id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO addresses (id, customer_id, street, city, zip_code, is_default)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAddressParams struct {
	ID         string       `db:"id" json:"id"`
	CustomerID string       `db:"customer_id" json:"customer_id"`
	Street     string       `db:"street" json:"street"`
	City       string       `db:"city" json:"city"`
	ZipCode    string       `db:"zip_code" json:"zip_code"`
	IsDefault  sql.NullBool `db:"is_default" json:"is_default"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.ExecContext(ctx, insertAddress,
		arg.ID,
		arg.CustomerID,
		arg.Street,
		arg.City,
		arg.ZipCode,
		arg.IsDefault,
	)
	return err
}

const insertCustomer = `-- name: InsertCustomer :exec
INSERT INTO customers (id, name, email, phone)
VALUES (?, ?, ?, ?)
`

type InsertCustomerParams struct {
	ID    string `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
	Phone string `db:"phone" json:"phone"`
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) error {
	_, err := q.db.ExecContext(ctx, insertCustomer,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
	)
	return err
}

const listAddressesByCustomerID = `-- name: ListAddressesByCustomerID :many
SELECT id, customer_id, street, city, zip_code, is_default
FROM addresses
WHERE customer_id = ?
`

type ListAddressesByCustomerIDRow struct {
	ID         string       `db:"id" json:"id"`
	CustomerID string       `db:"customer_id" json:"customer_id"`
	Street     string       `db:"street" json:"street"`
	City       string       `db:"city" json:"city"`
	ZipCode    string       `db:"zip_code" json:"zip_code"`
	IsDefault  sql.NullBool `db:"is_default" json:"is_default"`
}

func (q *Queries) ListAddressesByCustomerID(ctx context.Context, customerID string) ([]ListAddressesByCustomerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAddressesByCustomerIDRow
	for rows.Next() {
		var i ListAddressesByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Street,
			&i.City,
			&i.ZipCode,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET name = ?, email = ?, phone = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCustomerParams struct {
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
	Phone string `db:"phone" json:"phone"`
	ID    string `db:"id" json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.ID,
	)
	return err
}

const updateDefaultAddress = `-- name: UpdateDefaultAddress :exec
UPDATE addresses
SET is_default = (id = ?), updated_at = CURRENT_TIMESTAMP
WHERE customer_id = ?
`

type UpdateDefaultAddressParams struct {
	ID         string `db:"id" json:"id"`
	CustomerID string `db:"customer_id" json:"customer_id"`
}

func (q *Queries) UpdateDefaultAddress(ctx context.Context, arg UpdateDefaultAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateDefaultAddress, arg.ID, arg.CustomerID)
	return err
}
