// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Address struct {
	ID         string       `db:"id" json:"id"`
	CustomerID string       `db:"customer_id" json:"customer_id"`
	Street     string       `db:"street" json:"street"`
	City       string       `db:"city" json:"city"`
	ZipCode    string       `db:"zip_code" json:"zip_code"`
	IsDefault  sql.NullBool `db:"is_default" json:"is_default"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
}

type Cart struct {
	CustomerID   string         `db:"customer_id" json:"customer_id"`
	RestaurantID sql.NullString `db:"restaurant_id" json:"restaurant_id"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type CartItem struct {
	ID            int32          `db:"id" json:"id"`
	CustomerID    string         `db:"customer_id" json:"customer_id"`
	ProductID     string         `db:"product_id" json:"product_id"`
	Name          string         `db:"name" json:"name"`
	PriceAmount   float64        `db:"price_amount" json:"price_amount"`
	PriceCurrency string         `db:"price_currency" json:"price_currency"`
	Quantity      int32          `db:"quantity" json:"quantity"`
	Observation   sql.NullString `db:"observation" json:"observation"`
}

type Customer struct {
	ID        string       `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Email     string       `db:"email" json:"email"`
	Phone     string       `db:"phone" json:"phone"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type OutboxMessage struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	PublishedAt   sql.NullTime    `db:"published_at" json:"published_at"`
}
