// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: outbox.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (
    id, aggregate_type, aggregate_id, event_type, payload, correlation_id
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertOutboxMessageParams struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
	)
	return err
}

const listUnpublishedMessages = `-- name: ListUnpublishedMessages :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, correlation_id, created_at, published_at FROM outbox_messages
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListUnpublishedMessages(ctx context.Context, limit int32) ([]OutboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, listUnpublishedMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageAsPublished = `-- name: MarkMessageAsPublished :exec
UPDATE outbox_messages
SET published_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkMessageAsPublished(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markMessageAsPublished, id)
	return err
}
