// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	ClearAddresses(ctx context.Context, customerID string) error
	DeleteCart(ctx context.Context, customerID string) error
	DeleteCartItems(ctx context.Context, customerID string) error
	GetCartByCustomerID(ctx context.Context, customerID string) (Cart, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id string) (Customer, error)
	InsertAddress(ctx context.Context, arg InsertAddressParams) error
	InsertCart(ctx context.Context, arg InsertCartParams) error
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	InsertCustomer(ctx context.Context, arg InsertCustomerParams) error
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	ListAddressesByCustomerID(ctx context.Context, customerID string) ([]ListAddressesByCustomerIDRow, error)
	ListCartItemsByCustomerID(ctx context.Context, customerID string) ([]CartItem, error)
	ListUnpublishedMessages(ctx context.Context, limit int32) ([]OutboxMessage, error)
	MarkMessageAsPublished(ctx context.Context, id string) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateDefaultAddress(ctx context.Context, arg UpdateDefaultAddressParams) error
}

var _ Querier = (*Queries)(nil)
