// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, order_id, amount, status, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	ID        string       `db:"id" json:"id"`
	OrderID   string       `db:"order_id" json:"order_id"`
	Amount    int64        `db:"amount" json:"amount"`
	Status    string       `db:"status" json:"status"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.Amount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, amount, status, created_at, updated_at FROM payments WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, status, created_at, updated_at FROM payments WHERE order_id = ? LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (id, aggregate_type, aggregate_id, event_type, payload, correlation_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertOutboxMessageParams struct {
	ID            string          `db:"id" json:"id"`
	AggregateType string          `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string          `db:"aggregate_id" json:"aggregate_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID string          `db:"correlation_id" json:"correlation_id"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxMessage,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CorrelationID,
		arg.CreatedAt,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = ?, updated_at = ? WHERE id = ?
`

type UpdatePaymentStatusParams struct {
	Status    string       `db:"status" json:"status"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	ID        string       `db:"id" json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
