// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	GetPaymentByID(ctx context.Context, id string) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error)
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
